# Generated by Django 4.2 on 2023-05-06 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=40)),
                ('path', models.CharField(max_length=70)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=45)),
                ('original_file_name', models.CharField(max_length=35)),
                ('comment', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('unique_url', models.CharField(max_length=200)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='fstorage.storage_model')),
            ],
        ),
    ]
