# Generated by Django 4.2 on 2023-05-07 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fstorage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_file',
            name='file_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_file',
            name='last_download',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_file',
            name='size',
            field=models.DecimalField(decimal_places=10, default=11.5, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_file',
            name='upload_date',
            field=models.DateField(auto_now=True),
        ),
    ]
