# Generated by Django 4.2 on 2023-05-08 17:16

from django.db import migrations, models
import fstorage.models


class Migration(migrations.Migration):

    dependencies = [
        ('fstorage', '0002_user_file_file_path_user_file_last_download_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_file',
            name='file',
            field=models.FileField(upload_to=fstorage.models.directory_path),
        ),
        migrations.AlterField(
            model_name='user_file',
            name='last_download',
            field=models.DateField(null=True),
        ),
    ]
