# Generated by Django 4.2 on 2023-05-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fstorage', '0004_alter_user_file_comment_alter_user_file_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_file',
            name='comment',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='user_file',
            name='unique_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
