# Generated by Django 4.2 on 2023-05-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fstorage', '0006_user_file_ext_alter_user_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_file',
            name='original_file_name',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='user_file',
            name='size',
            field=models.DecimalField(decimal_places=12, max_digits=19, null=True),
        ),
    ]
